### ISSUE TITLE
New warning about Loopback 4.x get in the way of the output

### ISSUE THREAD

**Issue by HugoPoi** [strongloop/loopback-cli#100]
# Description/Steps to reproduce

1. npm install loopback-cli
1. npx lb export-api-def --json
1. Warning is printed in stdout, not stderr
  ```
  LoopBack 3 is in Maintenance LTS mode, only critical bugs and critical
  security fixes will be provided. The support ends in December 2020. We
  urge all LoopBack 3 users to migrate their applications to LoopBack 4
  as soon as possible. Refer to our Migration Guide for more information
  on how to upgrade: https://loopback.io/doc/en/lb4/migration-overview.html
  
  ...JSON_DATA...
  ```
  

# Expected result

The warning should be in stderr

**Comment by dhmlau** [comment]
@bajtos, what do you think?

**Comment by bajtos** [comment]
Thank you @HugoPoi for reporting the issue. I agree with you that the current behavior is not great and like your proposal to print the warning to `stderr`. Would you like to contribute the change yourself? See [Contributing code](https://loopback.io/doc/en/contrib/code-contrib.html) get started.
