### ISSUE TITLE
Add a version number

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback-cli#13]
- [ ] Bug
- [x ] Feature request

### Description of feature (or steps to reproduce if bug)

Add a way to display the current version.

lb -v

**Comment by bajtos** [comment]
This is already working AFAICT:

```
$ lb --version
2.5.0 (generator-loopback@3.7.0 loopback-workspace@3.40.1)
$ lb -v
2.5.0 (generator-loopback@3.7.0 loopback-workspace@3.40.1)
```

**Comment by cfjedimaster** [comment]
So when I type `lb -h`, I do not see this listed. Do you?

**Comment by bajtos** [comment]
Good catch. Can you open a new issue for that please?
