### ISSUE TITLE
Add commands to generate Bluemix artifacts for deployment automation and service bindings

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-cli#14]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

1. Refine the sample app as the template for adding Bluemix flavor to LB
2. Start with yeoman commands to generate manifest.yml
  - lb bluemix:manifest 
3. Generate .bluemix/pipeline.yml, toolchain.yml etc
  - CloudFoundry
  - IBM Container
4. Deploy to Bluemix & Create ToolChain
5. Discover/provision Bluemix services
6. Map Bluemix DB services to LoopBack datasources
7. More integration such as Auth, Monitoring, ...

Two possible modules:
- loopback-bluemix
- Corresponding bluemix generators in generator-loopback
See https://github.com/strongloop/loopback-example-bluemix

**Comment by superkhau** [comment]
@raymondfeng and @hacksparrow  to break this down into smaller stories.

**Comment by superkhau** [comment]
Timebox whatever time @hacksparrow is on for this sprint -- probably 4/5 days. @hacksparrow Please re-estimate this story.

**Comment by hacksparrow** [comment]
@superkhau the tasks are listed and updated here - https://github.com/strongloop/loopback-workspace/pull/436

**Comment by dhmlau** [comment]
With the priority to focus on LoopBack 4, we won't have the bandwidth to get to this in a near future.  I'd like to close this issue as `won't implement`.
