### ISSUE TITLE
Provide a "start" command

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-cli#15]
@lazaridis-com commented on [Sun Feb 12 2017](https://github.com/strongloop/loopback/issues/3200)

The `lb` command line tool should have a `start` command.

This would simplify the usage, especially for newcomers (they don't know much about the underlying stack).

Additionally, it would be more consistent in general (one command-line tool, "lb").

### Current Status

```shell
$ lb app todo
$ cd todo 
$ lb model
$ node .
```

### With "start" Command

```shell
$ lb app todo
$ cd todo 
$ lb model
$ lb start
```

**Comment by superkhau** [comment]
@lazaridis-com Good idea. Just to confirm though, `lb start` should basically map to `npm start` correct?

**Comment by raymondfeng** [comment]
I'm not sure about the value of `lb start` as it might mean multiple different things, such as:

- node .
- npm start
- strong-pm
- pm2
- docker run

**Comment by superkhau** [comment]
>lb start as it might mean multiple different things

Thats why I suggested mapping to `npm start` so the user can define what it means via typical node conventions.

**Comment by superkhau** [comment]
>Additionally, it would be more consistent in general (one command-line tool, "lb").

@lazaridis-com I don't think this will ever be the case unless we wrap all the `npm` commands as you'll still need to `npm install` your dependencies etc, meaning it'll never be "one command-line tool").

**Comment by lazaridis-com** [comment]
@superkhau, @raymondfeng - `lb start` should encapsulate the domain-knowledge, shielding this way the user from it (one less thing to remember).

`lb start` should be smart enough to detect what its sister-command `lb app` had created, and start it the right way.

I don't think that your Unix analogy is valid here. It's more about basic **product** usability&branding and (as said) shielding of 

`npm` is a tool. `node.js` is a tool. `LoopBack` is the king, which uses the underlying tools.

**Comment by superkhau** [comment]
@lazaridis-com It's more about do one thing well, which is to be the best API framework, not the best JavaScript runtime or Node.js package manager.

That said, we're open to opinions. Do you suggest shielding the user away from NPM and Node.js completely? Ie. What if you want to install a dependency for your LoopBack project? Do you now want a `lb install` command that maps to `npm install`? What about when you want to remove dependencies? Do you put in `lb rm` that maps to `npm rm` for that? And so forth.

**Comment by lazaridis-com** [comment]
@superkhau , I basically wanted just a "start" command for now, in order to be able to write simple beginner tutorials.

But to answer your question which goes into tool-design philosophies:

From a Product point of view, yes, LoopBack should be able to do nearly everything necessary for basic API development. Using wrappers means that lb can do some consistency-checking or other things (like making entries, anything), too.

Example:

```shell
lb install super-tool-a

#loopback responds with a message:

#"super-tool-a is a good one, but we have optimized loopback to work with super-tool-b.
#You continue with super-tool-a installation"?
```

A beginner or a lazy core-developer (like me) would be happy. A control-freakish core-developer (who knows 100% what he's doing) would yell and bypass the `lb install` command in future. Another beginner becomes a master in 3 months, and decide to use the underlying stuff directly. I myself do a full teach-in to JS, and then use naturally the underlying tools to have more control.

But as said, for now, the basic `lb start` command would really be enough (e.g. enabling a simple tutorial, which ends with "IBM has a nice tool which works nice with LoopBack, try it out at https://developer.ibm.com/apiconnect/getting-started/)

**Comment by superkhau** [comment]
@lazaridis-com Thank you for your detailed thoughts. It's an interesting perspective. I'm all for giving the people what they want. At the same time, we also try to scope down the features only the absolutely necessary. Of course the perspectives differ depending on how experienced you are as you described.

Let's get some more input here. As for my opinion now, I don't mind sugar api that delegates off to NPM/Node commands if it's simple to implement (and if you're willing to contribute it since it's obviously not at the top of our current priorities, but I respect that it might be on yours).

@bajtos What are you thoughts?

**Comment by bajtos** [comment]
I personally think that `lb start` is redundant and `node .` is more than good enough.

**Comment by superkhau** [comment]
@lazaridis-com Gonna close this as rejected, we can reopen this if we get more requests for this feature.

As a workaround, you're free to create your own bash alias to do what you want:

```
lb() {
  if [[ $@ == "start" ]]; then
    node .
  else
    lb $@
  fi
}
```

Note: I haven't tested the above, but it's probably something along those lines.

**Comment by lazaridis-com** [comment]
@bajtos , @superkhau , @raymondfeng - thank you for your time.

**Comment by lazaridis-com** [comment]
@bajtos , @superkhau , @raymondfeng - not sure who of you is closest to the Project Manager role.

Can please someone comment on this issue: #3199

**Comment by lazaridis-com** [comment]
@bajtos , @superkhau , @raymondfeng - not sure who of you is closest to the Project Manager role.

Can please someone comment on this issue: strongloop/loopback#3199

**Comment by superkhau** [comment]
@lazaridis-com -- @raymondfeng and @ritch would be closer to that role, but I work closely with @bajtos on community issues. It is definitely something we're addressing, but alas resources are pulling us in many directions. The project is definitely not dead and there is a lot of work being done on the next version of LoopBack. Your concern in #3199 is definitely one of the top priorities on our list. I will comment a bit more over there.
