### ISSUE TITLE
Odd output making a new app

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback-cli#16]
### Bug or feature request

- [ x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

I just ran "lb", and before the Yeoman hat man, some odd output was spit out that I've not seen before:

![image](https://cloud.githubusercontent.com/assets/393660/23131773/ed04a222-f750-11e6-8434-9c8d4044478b.png)

It didn't break anything as far as I can tell.

### Additional information (Node.js version, LoopBack version, etc)

lb -v returns 1.0.0.
node -v returns 6.9.2.

**Comment by bajtos** [comment]
@cfjedimaster is this issue still relevant? How can we reproduce it ourselves?
