### ISSUE TITLE
The lb command doesnt honour the options that most examples on the Internet still using slc provide

### ISSUE THREAD

**Issue by pastcompute** [strongloop/loopback-cli#17]
### Feature Request - add command line options to avoid being prompted

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

I have just started using loopback and most of the tutorials I have found seem to have two modes, one using a command called `slc` (which is deprecated?) and this tool `lb`. For example, https://strongloop.com/strongblog/postgresql-node-js-apis-loopback-connector/

I'm very used to scripting tasks I repeat or up-arrowing to a prior command , and find it a little unproductive having to answer prompts all the time. I know it remembers answers but I would still be useful to be able to enter a command such as `lb datasource accountDB --connector postgresql --quiet` and not be prompted to confirm what I just typed. If anyone ever wanted to automated creating a skeleton into docker or a vm they would not be able to do that either

**Comment by bajtos** [comment]
Hi @pastcompute, your request makes a lot of sense, in fact our @rmg has mentioned this idea to us too.

Would you like to contribute this improvement yourself? The code changes will need to happen in https://github.com/strongloop/generator-loopback

**Comment by pastcompute** [comment]
I could have a go but it would be in a little while when I have time
