### ISSUE TITLE
Postgresql datasource prompt is confusing, after typing in the connection string I again get prompted for the host, etc.

### ISSUE THREAD

**Issue by pastcompute** [strongloop/loopback-cli#18]
### Bug 

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

This is probably a nice to have.

The datasource cli prompt requests a datasource URI and provides an example and then pauses, so presumably I should type in a datasource. Except when I do, it still prompts me to type in all the components. The wording hints at 'url to override', it would be useful to avoid having to retype all the parts of it if I actually want them to be the same as the url.

### Expected result

    demo@dev:~/backend$ lb datasource hello
    Enter the data-source name: hello
    ? Select the connector for hello: PostgreSQL (supported by StrongLoop)
    Connector-specific configuration:
    ? Connection String url to override other settings (eg: postgres://username:password@localhost/database, ENTER for prompt): postgres://username:password@localhost/hello

or, if I want to be prompted for the components:

    demo@dev:~/backend$ lb datasource hello
    Enter the data-source name: hello
    ? Select the connector for hello: PostgreSQL (supported by StrongLoop)
    Connector-specific configuration:
    ? Connection String url to override other settings (eg: postgres://username:password@localhost/database, ENTER for prompt): 
    ? host: localhost
    ? port: 5432
    ? user: username
    ? password: ********
    ? database: hello

### Actual result (if bug)

    demo@dev:~/backend$ lb datasource hello
    Enter the data-source name: hello
    ? Select the connector for hello: PostgreSQL (supported by StrongLoop)
    Connector-specific configuration:
    ? Connection String url to override other settings (eg: postgres://username:password@localhost/database): postgres://username:password@localhost/hello
    ? host: localhost
    ? port: 5432
    ? user: username
    ? password: ********
    ? database: hello

### Additional information (Node.js version, LoopBack version, etc)

Installed loopback as per https://loopback.io/doc/en/lb3/Installation.html
Node is 7.x on debian 8 in a virtualbox guest and loopback project using 3.x

**Comment by pastcompute** [comment]
Perhaps it is the text that is confusing, it says 'to override other components' but it still feels wrong to have to type everything in twice

**Comment by bajtos** [comment]
I am afraid this is intentional, providing both URL and individual settings at the same time is a valid use case - see https://github.com/strongloop/loopback-boot/issues/4#issuecomment-191289532.

**Comment by pastcompute** [comment]
@bajtos ok thanks.

In any case I've since learned to just hand write json files without needing the wizards, but others may google this and be informed
