### ISSUE TITLE
Datasource generator fails on command/bluemix-beta branch

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-cli#23]
Following the [instructions to install the Bluemix tooling](https://github.com/strongloop/loopback.io/wiki/LoopBack-Bluemix-native-tooling) 

After installing via `npm install -g strongloop/loopback-cli#command/bluemix-beta`

```
$ lb datasource
Unknown command "datasource"
Run "/usr/local/bin/lb --commands" to print the list of available commands.
```

@hacksparrow indicated he could reproduce.

@superkhau FYI

**Comment by hacksparrow** [comment]
Please disregard the beta branch. It's already fixed on `command/bluemix`.

@crandmck @superkhau
