### ISSUE TITLE
`lb` command with no args should show usage/help menu

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-cli#3]
Most command line apps show usage/help menu when executing without options/args. For example:

```
$ brew

Example usage:
  brew search [TEXT|/REGEX/]
  brew (info|home|options) [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install -vd FORMULA

Developers:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]
  https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

Further help:
  man brew
  brew help [COMMAND]
  brew home
```

I find it weird that we don't default to the typical linux/unix conventions. Of course, this is probably a nit since the next typical thing anyone on command line would default to using is `lb -h` or `lb --help`. Might be more painful to force users to do `lb app` to create new apps.

@bajtos Thoughts?

**Comment by bajtos** [comment]
I don't have a strong opinion. @ritch do you have one? If not, then I am happy to proceed with @superkhau's proposal.

**Comment by superkhau** [comment]
This might not be worth the effort anyways at this time (we have bigger fish to fry). I'll just close this as no one else is really complaining about CLI usage yet -- defaulting to interactive prompts seems to be working for years already.
