### ISSUE TITLE
CLI prints "cf login" message even when don't use --bluemix

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-cli#30]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

After updating `loopback-cli`, now when I do any of `lb app`, `lb model`,  or`lb datasource`  I get the info message:
```
Please use `cf login` to log into Bluemix first.
```
Even if I don't use `--bluemix`.   

Also, the same thing happens with `lb bluemix`.  For all these commands, it displays this message even if you are just getting CLI help with `-h`.
@hacksparrow @raymondfeng

**Comment by raymondfeng** [comment]
@crandmck It should be fixed now. Can you try `npm -g loopback-cli` and test again?

**Comment by crandmck** [comment]
That seems to have fixed it, thanks.  I'll close this.
