### ISSUE TITLE
Failure to install due to node-gyp

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback-cli#33]
### Bug or feature request

- [ X] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Trying to install globally (and I tried to uninstall first) gives an error related to node-gyp:

/usr/bin/lb -> /usr/lib/node_modules/loopback-cli/bin/loopback-cli.js

> ursa@0.9.4 install /usr/lib/node_modules/loopback-cli/node_modules/ursa
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/loopback-cli/node_modules/ursa/build'
gyp ERR! System Linux 4.4.0-43-Microsoft
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/loopback-cli/node_modules/ursa
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules/loopback-cli/node_modules/ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

### Expected result

For it not to error. ;)

### Actual result (if bug)

See stack trace above.

### Additional information (Node.js version, LoopBack version, etc)

Node is v8.

**Comment by raymondfeng** [comment]
What you see is not fatal. `ursa` is a binary module that doesn't work on Windows without openssl.

**Comment by cfjedimaster** [comment]
Gotcha - and sorry - a bit after I tested lb, and it worked, but ran to a lunch date before closing this issue.
