### ISSUE TITLE
lb --version is not in the CLI help

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback-cli#35]
### Bug or feature request

- [ x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

When doing lb -h, you do not see the --version flag documented

### Expected result

It should be.

### Actual result (if bug)

It isn't.

**Comment by dhmlau** [comment]
@cfjedimaster , would you like to submit a PR? :)

**Comment by cfjedimaster** [comment]
Nah - as it stands - I'm not sure if this even applies to the CLI for v4. (And I'm not doing anything much with LB these days.)

**Comment by dhmlau** [comment]
@cfjedimaster , it won't apply to v4 because it uses a different module  `@loopback/cli`.

**Comment by crshnburn** [comment]
loopback/generator-loopback#350 opened to add this functionality.

**Comment by dhmlau** [comment]
Closed as resolved.  @crshnburn , thanks for your contribution!
