### ISSUE TITLE
Loopback cli crashing on node 8.1.1 on windows

### ISSUE THREAD

**Issue by prateekrastogi** [strongloop/loopback-cli#37]
During loopback-cli installation on windows optional dependecy ursa always fail to install. But, cli works fine on node 6 , but after upgrading to node 8 it hangs on the second input option in model, property,app commands. So, i was forced to downgrade my node version.

**Comment by raymondfeng** [comment]
Can you confirm that your node version is `8.1.1`? There was a bug in `node 8.1.0` that hangs the CLI.

**Comment by prateekrastogi** [comment]
tried it with 8.1.2. It's working fine.
