### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by itcurves** [strongloop/loopback-cli#39]
on : 

npm install -g loopback-cli

Error:
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\USER\AppData\Roaming\npm\node_modul
es\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]

I used this command before with no issues but this start happening now ( I am trying to configure a new machine)

And reason or guide what I am missing?

**Comment by raymondfeng** [comment]
The optional dependency failure is expected on Windows. It's just a warning and should not fail the installation. Do you see otherwise?

**Comment by Jeff-Lewis** [comment]
https://github.com/quartzjer/ursa/pull/149

**Comment by halinh12310** [comment]
@itcurves you can down lib from [here](https://github.com/ReadyTalk/win32/blob/master/msvc/lib/libeay32.lib) and copy to `C:\OpenSSL-Win32\lib` folder.
P/s: Sorry for my bad english. So I Hope this helps you

**Comment by dhmlau** [comment]
Closing it as resolved.
