### ISSUE TITLE
lb <command | appName>

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-cli#41]
It would be very convenient to be able to do:

```sh
lb my-app
```

In `lb <param>`, we check if `param` is a `lb` command, if not, we assume it is the name of the app/dir.

@raymondfeng @bajtos thoughts?

### Bug or feature request

- [ ] Bug
- [x] Feature request

**Comment by dhmlau** [comment]
We have this feature in LoopBack4! 
Since we are focusing on LB4 which has GA'ed, I don't think we'll have the bandwidth to get this done in a reasonable timeframe.  As a result, I'd like to close this issue. Thanks.
