### ISSUE TITLE
lb export-api-def never returns in NodeJS command prompt

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/loopback-cli#50]
# Description/Steps to reproduce

Running this command 

```
lb export-api-def -o test.yml
```
never returns. The file is properly generated, but the command needs to be killed.

# Link to reproduction sandbox

I'm not sur how to provide a reproduction sandbox. I'm running on Windows in NodeJS command prompt. Any environment with similar properties should reproduce the issue
```
$ node -v
v6.11.0
$ npm -v
3.10.10
```

# Expected result

I expect the command to complete without hanging.

# Additional information

```
$ node
> console.log(process.platform, process.arch, process.versions.node)
win32 x64 6.11.0
```
```
$ npm ls --prod --depth 0
+-- async@2.4.1
+-- bull@3.0.0-rc.3
+-- compression@1.6.2
+-- cors@2.8.3
+-- google-auto-auth@0.7.0
+-- helmet@1.3.0
+-- ioredis@3.1.1
+-- lodash@4.17.4
+-- loopback@2.38.3
+-- loopback-boot@2.24.1
+-- loopback-component-explorer@2.7.0
+-- loopback-component-storage@3.2.0
+-- loopback-datasource-juggler@2.54.2
+-- moment@2.18.1
+-- rrule@2.2.0
+-- serve-favicon@2.4.3
+-- sinon@2.3.5
+-- strong-error-handler@2.1.0
+-- superagent@3.5.2
`-- uuid@3.1.0
```

**Comment by bajtos** [comment]
Hello, thank you for reporting this issue. Is it possible that your application is allocating resources running in background (e.g. a connection pool used by a database driver behind a LoopBack datasource) that's blocking the process from exiting? You can verify this assumption by running the following command in your application/project directory:

```
node -e "require('./')"
```

If the command hangs, then it's your application what's blocking `lb export-api-def` from exiting. This can be fixed e.g. by modifying `lb export-api-def` to explicitly kill the process once the spec file was written - would you like to contribute the fix yourself?

**Comment by Overdrivr** [comment]
I've made a PR, but I'm not sure how to test this feature. More specifically, how to generate a app that never finishes loading using the template from `loopback-workspace`. Let me know if you have something obvious in mind.

**Comment by bajtos** [comment]
Closing as fixed by https://github.com/strongloop/generator-loopback/pull/316
