### ISSUE TITLE
lb model --ls

### ISSUE THREAD

**Issue by Cooker-Monster** [strongloop/loopback-cli#55]
Bug or feature request

    [ ] Bug
    [x] Feature request

Description of feature (or steps to reproduce if bug)

Could be handy to have new cli model option to __list defined models__ in the project such as 
>lb model --ls

Expected result (maybe with build-in model inheritence) :

>Account ➡  User
>Receipe ➡ PersistedModel

**Comment by dhmlau** [comment]
@Cooker-Monster, thanks for your suggestion.  At this point, it will be a low priority item for us.  Would you like to submit a PR for this feature?  Thanks.

**Comment by Cooker-Monster** [comment]
@dhmlau, no PR yet, but as I already wrote a plantuml file generator base on models, it could be a baseline...

**Comment by dhmlau** [comment]
@Cooker-Monster, I'm marking this issue as `help wanted`.  Thanks :)
