### ISSUE TITLE
lb swagger using incorrect configuration directories

### ISSUE THREAD

**Issue by doowb** [strongloop/loopback-cli#56]
# Description/Steps to reproduce

I've configured my application using the options passed to `loopback-boot` so I can separate my models from other pieces of the configuration. The server will start and find all of the configuration files necessary to run.

I also want to use a swagger file and `lb swagger` to generate the model configurations, but since the default configuration is different from what's passed to `loopback-boot`, I'm ending up with empty configuration files and mode configuration files in the wrong directories.

# Expected result

I'd expect to be able to provide `lb swagger` with the same configuration directories that I can provide `loopback-boot` to ensure the models are put in the correct places.

# Additional information

It does seem like `lb swagger` is finding some of the configuration files because the list of models (including ones that already exist in `model-config.json`) and the list of datasources are correct when prompted to select models and datasources.

**output from commands:**

```
darwin x64 8.4.0
├── loopback@3.15.0
├── loopback-boot@2.26.2
```

**Comment by KristofMorva** [comment]
It's applied to other commands as well. `lb model` returns `"Warning: Found no data sources to attach model. There will be no data-access methods available until datasources are attached."` if the `datasources.json` is not in the default location.
