### ISSUE TITLE
loopback cli doesnt work globally

### ISSUE THREAD

**Issue by remith** [strongloop/loopback-cli#58]
# Description/Steps to reproduce

However when I try to run the command lb it says

The program 'lb' is currently not installed. You can install it by typing:
sudo apt install live-build

If i go to the shared library and run lb using ./lb it works, i am not sure if I shoud move the directories to /opt and then try, please help

**Comment by dhmlau** [comment]
@remith , how did you install the command?  `npm i -g loopback-cli` ?
what OS are you running on?

**Comment by remith** [comment]
I am using Ubuntu 16.04. Fixed it by adding the path to .bashrc. Somehow it
was not setting the environment variables automatically.

Thanks
Remith Ravindran

On 08-Feb-2018 12:42 am, "Diana Lau" <notifications@github.com> wrote:

@remith <https://github.com/remith> , how did you install the command? npm
i -g loopback-cli ?
what OS are you running on?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/strongloop/loopback-cli/issues/58#issuecomment-363877543>,
or mute the thread

**Comment by dhmlau** [comment]
@remith , it's good to hear.  Is this issue good to close then?

**Comment by remith** [comment]
Yes.

**Comment by justin2476** [comment]
hi  @remith ,

Can you please tell me how to set the path to .bashrc . i have the same issue.

Thanks
Justin

**Comment by remith** [comment]
Locate where the package is installed using 'which packagename' command and
then copy that path into .bashrc file.

1. which lb
You will get a path,copy that path
2. Go to home, open the .bashrc file using any editor eg. vi .bashrc
3. Add the below lines to the end of the file,
export PATH= your path
Eg.
export PATH=/usr/local/lib/node_modules/node/bin/lb

Let me know if that doesn't work

Thanks,
Remith Ravindran

**Comment by sirajalam049** [comment]
Somehow I installed live-build, now even after adding loobpack path, `lb` command is still takes by live-build, even I have uninstalled it, any solution?
