### ISSUE TITLE
Not able to install loopback-cli in ubuntu 17.10

### ISSUE THREAD

**Issue by KailashRajPradhan** [strongloop/loopback-cli#62]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

version  linux x64 9.5.0

9956 silly extract ajv@^5.1.0 extracted to /home/kailash/.npm-global/lib/node_modules/.staging/ajv-e4825714 (1062ms)
9957 silly extract lodash@3.6.0 extracted to /home/kailash/.npm-global/lib/node_modules/.staging/lodash-89021040 (1172ms)
9958 silly extract lodash@^3.10.0 extracted to /home/kailash/.npm-global/lib/node_modules/.staging/lodash-1199bfc9 (1394ms)
9959 verbose stack Error [ERR_STREAM_WRITE_AFTER_END]: write after end
9959 verbose stack     at writeAfterEnd (_stream_writable.js:237:12)
9959 verbose stack     at PassThrough.Writable.write (_stream_writable.js:287:5)
9959 verbose stack     at PassThrough.Writable.end (_stream_writable.js:573:10)
9959 verbose stack     at ReadEntry.entry.on (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
9959 verbose stack     at ReadEntry.emit (events.js:165:20)
9959 verbose stack     at ReadEntry.emit (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
9959 verbose stack     at ReadEntry.[maybeEmitEnd] (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
9959 verbose stack     at ReadEntry.end (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
9959 verbose stack     at Unpack.[consumeBody] (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
9959 verbose stack     at Unpack.[consumeChunkSub] (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
9959 verbose stack     at Unpack.[consumeChunk] (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
9959 verbose stack     at Unzip.(anonymous function).on.chunk (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
9959 verbose stack     at Unzip.emit (events.js:160:13)
9959 verbose stack     at Unzip.emit (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
9959 verbose stack     at Unzip.write (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
9959 verbose stack     at Unzip.write (/home/kailash/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
9960 verbose cwd /home/kailash
9961 verbose Linux 4.13.0-38-generic
9962 verbose argv "/home/kailash/.npm-global/lib/node_modules/node/bin/node" "/home/kailash/.npm-global/bin/npm" "install" "-g" "loopback-cli"
9963 verbose node v9.5.0
9964 verbose npm  v6.0.0
9965 error code ERR_STREAM_WRITE_AFTER_END
9966 error write after end
9967 verbose exit [ 1, true ]

**Comment by dhmlau** [comment]
@KailashRajPradhan , have you tried if it works for Node 8.x? 
I did a search, it might be related to: https://github.com/JoshKaufman/ursa/issues/167

**Comment by dhmlau** [comment]
@KailashRajPradhan , do you still encounter this issue with Node 8?

**Comment by raideltorres** [comment]
hi I was also having a lot of issues which I resolved by using node v8, but it will be nice to fix this for v10

```
CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc:389:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->n = BN_bin2bn(data_n, n_length, NULL);
            ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:390:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->e = BN_bin2bn(data_e, e_length, NULL);
            ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:407:35: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    if ((obj == NULL) || (obj->rsa->d != NULL)) {
                                  ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:536:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->e);
                                 ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:552:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->d);
                                 ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:567:34: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    bignumToBuffer(args, obj->rsa->n);
                                 ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1218:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1219:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1220:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->p = p;
                ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1221:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->q = q;
                ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1222:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmp1 = dp;
                ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1223:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->dmq1 = dq;
                ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1224:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->iqmp = inverseQ;
                ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1225:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->d = d;
                ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1270:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->n = modulus;
                ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:1271:17: error: member access into incomplete type 'RSA' (aka 'rsa_st')
        obj->rsa->e = exponent;
                ^
/Users/Beztia/.node-gyp/10.1.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
16 errors generated.
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Beztia/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Users/Beztia/.nvm/versions/node/v10.1.0/bin/node" "/Users/Beztia/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Beztia/.nvm/versions/node/v10.1.0/lib/node_modules/loopback-cli/node_modules/ursa
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

```

**Comment by dhmlau** [comment]
@KailashRajPradhan , good to hear that it's working for you for Node 8.  In the discussion thread https://github.com/JoshKaufman/ursa/issues/167, it doesn't seem like it's related to LoopBack, so I'm afraid that this is not something we can fix. 

As a result, I'd like to close this issue as resolved.  Please follow the discussion over there to find out the resolution.  Thanks!
