### ISSUE TITLE
lb relations ignores models from paths other than common/models

### ISSUE THREAD

**Issue by VictorVanDoom** [strongloop/loopback-cli#66]
# Description/Steps to reproduce

According to the documentation, it should be possible to apply a folder-structure to the common-models folder by adding the corresponding paths to the model-config json. This seems to be working from a loopback point of view. However, as soon as I move my models into a subfolder, I no longer can use loopback-cli to i.e setup model-relations, as it cannot see anything except the common-models folder.

Reproduction:

1. Move arbitrary model from common/model to common/model/test
2. Update model-config.json by adding common/model/test to _meta:sources
3. Run lb relation

No models are shown.

# Expected result
Should show models from common/model/test folder

# Additional information
darwin x64 8.1.3
├── loopback@3.19.0
├── loopback-boot@2.27.1
├── loopback-cascade-delete-mixin@1.3.1
├── loopback-component-explorer@4.3.0
├── loopback-connector-mongodb@3.4.3

**Comment by dhmlau** [comment]
@hacksparrow , could you please take a look when you have a chance?  Thanks!

**Comment by hacksparrow** [comment]
Yes, not showing up on `lb relation`. Looking into it.
