### ISSUE TITLE
Unable to install loopback-cli

### ISSUE THREAD

**Issue by nkanat** [strongloop/loopback-cli#72]
While running installation command : npm install -g loopback-cli

Ends with following error : 

npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm ERR! Unexpected end of JSON input while parsing near '...dA5qu8i3su88JtUNyXRFL'

From Log file : 

1767 http fetch GET 200 https://registry.npmjs.org/ignore 11ms (from cache)
1768 silly fetchPackageMetaData error for ignore@^3.3.5 Unexpected end of JSON input while parsing near '...dA5qu8i3su88JtUNyXRFL'
1769 silly pacote range manifest for dir-glob@^2.0.0 fetched in 14ms
1770 silly resolveWithNewModule dir-glob@2.0.0 checking installable status
1771 silly pacote range manifest for fast-glob@^2.0.2 fetched in 15ms
1772 silly resolveWithNewModule fast-glob@2.2.2 checking installable status
1773 silly pacote range manifest for slash@^1.0.0 fetched in 15ms
1774 silly resolveWithNewModule slash@1.0.0 checking installable status
1775 timing stage:rollbackFailedOptional Completed in 0ms
1776 timing stage:runTopLevelLifecycles Completed in 6622ms
1777 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...dA5qu8i3su88JtUNyXRFL'
1777 verbose stack     at JSON.parse (<anonymous>)
1777 verbose stack     at parseJson (C:\Users\nkanat\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
1777 verbose stack     at consumeBody.call.then.buffer (C:\Users\nkanat\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50) @slnode  Could you please check this ?

**Comment by Laxmikant04** [comment]
I am also facing similar issue while installing - npm install -g loopback-cli

**Comment by hacksparrow** [comment]
@Laxmikant04 please share the error message, the OS name and version, the node version, and npm version on your machine.
