### ISSUE TITLE
Prototype pollution in lodash via strong-docs > dox > jsdoctypeparser > lodash

### ISSUE THREAD

**Issue by ashokkumarsand** [strongloop/loopback-cli#74]
# Description/Steps to reproduce
1. Update loopback/cli to 1.0.1
2. Create the new application with lb4 

[!] 1 vulnerability found [2607 packages audited]
    Severity: 1 Low
    Run `npm audit` for more detail

# Link to reproduction sandbox

# Expected result
package must be free from vulnerability 

# Additional information

**Comment by dhmlau** [comment]
@jannyHou , could you PTAL? Thanks.

**Comment by dhmlau** [comment]
@ashokkumarsand , thanks for providing the output. From looking at your above comment, I think @raymondfeng will look into it.  Thanks.

**Comment by dhmlau** [comment]
Related to PR https://github.com/strongloop/loopback-next/pull/1903

**Comment by dhmlau** [comment]
@raymondfeng, I'm assigning this to you since you're working on a PR already. Thanks.

**Comment by hgezim** [comment]
I'm seeing 2 of these. Can be fixed by upgrading to lodash>=4.17.11
