### ISSUE TITLE
Unable to generate repository using lb4 command

### ISSUE THREAD

**Issue by ashokkumarsand** [strongloop/loopback-cli#75]
# Description/Steps to reproduce
113071-MBP15:reporting asand$ lb4 --version
@loopback/cli version: 1.0.1

@loopback/* dependencies:
  - @loopback/authentication: ^1.0.1
  - @loopback/boot: ^1.0.1
  - @loopback/build: ^1.0.0
  - @loopback/context: ^1.0.0
  - @loopback/core: ^1.0.0
  - @loopback/metadata: ^1.0.0
  - @loopback/openapi-spec-builder: ^1.0.0
  - @loopback/openapi-v3-types: ^1.0.0
  - @loopback/openapi-v3: ^1.0.1
  - @loopback/repository-json-schema: ^1.0.1
  - @loopback/repository: ^1.0.1
  - @loopback/rest: ^1.0.1
  - @loopback/testlab: ^1.0.0
  - @loopback/docs: ^1.0.1
  - @loopback/example-hello-world: ^1.0.1
  - @loopback/example-log-extension: ^1.0.1
  - @loopback/example-rpc-server: ^1.0.0
  - @loopback/example-todo: ^1.0.1
  - @loopback/example-soap-calculator: ^1.0.1
  - @loopback/service-proxy: ^1.0.0
  - @loopback/http-caching-proxy: ^1.0.0
  - @loopback/http-server: ^1.0.0
  - @loopback/example-todo-list: ^1.0.1
  - @loopback/dist-util: ^0.4.0
113071-MBP15:reporting asand$ lb4 datasource
? Datasource name: oracle
? Select the connector for oracle: Oracle (supported by StrongLoop)
? Connection String tns (eg: DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=MY_HOST)(PORT=MY_PORT))(CONNECT_DATA=(SERVER=DEDICATED)(SE
RVICE_NAME=MY_DB))): 
? host: <My_URL>
? port: 1521
? user: <My_USER>
? password: [hidden]
? database: demonlord
   create src/datasources/oracle.datasource.json
   create src/datasources/oracle.datasource.ts

> oracledb@2.3.0 install /Users/asand/workspace/reporting/node_modules/oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb Oracledb downloaded
oracledb Verifying installation
oracledb Binary SHA matches SHA in SHASUMS256.txt
oracledb 
oracledb ********************************************************************************
oracledb ** Node-oracledb 2.3.0 installation complete for Node.js 8.11.4 (darwin, x64)
oracledb **
oracledb ** To use the installed node-oracledb:
oracledb ** - You need to have the Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
oracledb **   Download from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html
oracledb **
oracledb ** Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
oracledb ********************************************************************************

npm WARN reporting@1.0.0 No license field.

+ loopback-connector-oracle@4.1.1
added 2 packages in 7.38s
[!] 1 vulnerability found [2755 packages audited]
    Severity: 1 Low
    Run `npm audit` for more detail

   update src/datasources/index.ts

Datasource oracle was created in src/datasources/

113071-MBP15:reporting asand$ lb4 model
? Model class name: ReportEngineJob
? Please select the model base class Entity
Let's add a property to ReportEngineJob
Enter an empty property name when done

? Enter the property name: id
? Property type: string
? Is id the ID property? Yes
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to ReportEngineJob
Enter an empty property name when done

? Enter the property name: status
? Property type: string
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to ReportEngineJob
Enter an empty property name when done

? Enter the property name: resourceId
? Property type: string
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to ReportEngineJob
Enter an empty property name when done

? Enter the property name: resourcePath
? Property type: string
? Is it required?: Yes
? Default value [leave blank for none]: 

Let's add another property to ReportEngineJob
Enter an empty property name when done

? Enter the property name: 
   create src/models/report-engine-job.model.ts
   update src/models/index.ts

Model ReportEngineJob was created in src/models/

113071-MBP15:reporting asand$ lb4 repository
? Please select the datasource OracleDatasource
? Select the model(s) you want to generate a repository 
Generation is aborted: Error: You did not select a valid model

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
Closing as duplicate of https://github.com/strongloop/loopback-connector-oracle/issues/168.
