### ISSUE TITLE
Publish a new version of loopback-cli using dependency generator-loopbak@6.x

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-cli#76]
# Description/Steps to reproduce

Publish a new version of loopback-cli using dependency generator-loopbak@6.x

Related PR: https://github.com/strongloop/loopback-cli/pull/71

# Acceptance Criteria:

- [x] Finish PR https://github.com/strongloop/loopback-cli/pull/71 (have 2 test failures)
- [x] Release a new major version of loopback-cli

**Comment by dhmlau** [comment]
@jannyHou , if there's nothing else in addition we need to do besides publishing, I'd move this task directly to backlog. thanks.

**Comment by jannyHou** [comment]
> I'd move this task directly to backlog. 

👍 sounds good.

**Comment by bajtos** [comment]
@jannyHou @dhmlau it would be great to update README with an LTS notice before making the new release. See https://github.com/strongloop/loopback-next/issues/1802 and https://github.com/strongloop/loopback-swagger/pull/133/files for an example of what changes to make.

**Comment by jannyHou** [comment]
Closing since PRs merged.
