### ISSUE TITLE
Not able to create model's properties using loopback-cli

### ISSUE THREAD

**Issue by certong0507** [strongloop/loopback-cli#79]
<img width="1025" alt="screenshot 2018-11-17 at 3 10 15 pm" src="https://user-images.githubusercontent.com/29158694/48658332-edb87a80-ea7a-11e8-921d-aa0c9420968d.png">

__loopback: 3.X__
__OS: macMojave 10.14.1__
__npm -v: 6.4.1__
__node -v: 8.12.0__

__Error thrown while creating model's properties:__

(node:1219) UnhandledPromiseRejectionWarning: TypeError: this.invoke is not a function
    at ModelGenerator.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/generator-loopback/model/index.js:362:14)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
 
This happened while I following the instruction for creating model from the official website (https://loopback.io/doc/en/lb3/Create-a-simple-API.html).

Anyone have any ideas on how to fix this?

**Comment by dhmlau** [comment]
seems like it's working before the semver-major release, i.e. `loopback-cli@4.2.1`. 
@jannyHou , could you please take a look? Thanks.

**Comment by jannyHou** [comment]
@certong0507 Thanks for catching it, the model generator invokes the property generator at [line 362](https://github.com/strongloop/generator-loopback/blob/master/model/index.js#L362), seems the internal invoke doesn't work in the new release, I am going to fix it now. 

As a workaround, can you try to run the property generator separately?

- When you run `lb model`, don't create property with it, which means when you see the property prompts like below, just push enter without typing any word.

  > Let's add some CoffeeShop properties now.
      Enter an empty property name when done.

- run `lb property` and select your created model to add properties.

**Comment by jannyHou** [comment]
@certong0507 The fix is released as generator-loopback@6.0.2
see https://github.com/strongloop/generator-loopback

Please re-install `loopback-cli` to get the latest dependency `generator-loopback`

**Comment by jannyHou** [comment]
I am closing this issue since it's fixed. Feel free to reopen it if you still see the bug.
