### ISSUE TITLE
How to install Angular SDK with new CLI

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-cli#8]
I don't believe this CLI package will install the `lb-ng` tool, as the `strongloop` package does.  
So, do we simply tell people to do `npm i loopback-sdk-angular` or what?  Will that even work?

@bajtos

**Comment by bajtos** [comment]
> So, do we simply tell people to do npm i loopback-sdk-angular or what? Will that even work?

Good question! One can install `lb-ng` using the following command:

```sh
$ npm install -g loopback-sdk-angular-cli
```

**Comment by crandmck** [comment]
Thanks, I'll change that in the docs, when I update them for this CLI.

**Comment by crandmck** [comment]
Done
