### ISSUE TITLE
lp: Error - no default destination available. error.

### ISSUE THREAD

**Issue by serkandemirel0420** [strongloop/loopback-cli#80]
It installs with few warning but it does not work. I believe its some kind of name collusion, not sure though.

**Comment by jannyHou** [comment]
hi @serkandemirel0420 could you provide more details? Like the steps to reproduce your error or screenshots?

**Comment by serkandemirel0420** [comment]
`npm install -g loopback-cli`

then

> `lp tt`
lp: Error - unable to access “tt” - No such file or directory

>`lp test`
lp: Error - no default destination available.
