### ISSUE TITLE
Json file formatted as single line

### ISSUE THREAD

**Issue by patrykwegrzyn** [strongloop/loopback-cli#81]
Every time when i create model on datasource via cli all `json` files are formatted to a single line

This is very annoying and makes hard to work with model definitions.

tested on `v5.0.0` and `v4.2.1` 

example 
```json
{"db":{"name":"db","connector":"memory"},..}
```
instead of 
```json
{
  "db": {
    "name": "db",
    "connector": "memory"
  }
..
}
```

**Comment by abmj1979** [comment]
Same thing here.

**Comment by saywow** [comment]
which platform are you using? windows? mac or linux?

**Comment by abmj1979** [comment]
@saywow i'm using Windows 10, on node 8.

**Comment by jimmycarlinco** [comment]
Same happening here!

**Comment by saywow** [comment]
interesting.. this may be windows specific then.. we will check it out. Thank you for your information.

**Comment by raymondfeng** [comment]
Please make sure `loopback-workspace@4.5.2` is picked up. You can run `npm ls loopback-workspace` to confirm.
