### ISSUE TITLE
Can't install loopback-cli

### ISSUE THREAD

**Issue by matiasx1998** [strongloop/loopback-cli#87]
# Description/Steps to reproduce

I can't install loopback-cli
[cmd](https://prnt.sc/nw5kky)
[log](https://pastebin.com/3axuCDq3)

help please

**Comment by dhmlau** [comment]
@matiasx1998, there're a few steps to do before installing `loopback-cli` as suggested in 
https://github.com/strongloop/loopback-cli/issues/69#issuecomment-455882987
It's been verified by the community users, and I just tried it as well. 
The key for me is to Install OpenSSL 1.0.2s 64bit from the installer here: https://slproweb.com/products/Win32OpenSSL.html  (1.0.2q mentioned in the above comment no longer exist but 1.0.2s worked for me). 

Hope it helps.

**Comment by matiasx1998** [comment]
I have the same version of OpenSSL and Python 2.7 and still doesn't work.

**Comment by matiasx1998** [comment]
please help

**Comment by raymondfeng** [comment]
We're trying to remove ursa dependency - see https://github.com/strongloop/strong-soap/pull/224

**Comment by raymondfeng** [comment]
We just released `strong-soap@1.20.0`. Can you try run `npm i -g loopback-cli` again?

**Comment by dhmlau** [comment]
Closing as resolved. See [above comment](https://github.com/strongloop/loopback-cli/issues/87#issuecomment-498114452).  @matiasx1998, if you still encounter this issue, please open a new ticket. Thanks.
