### ISSUE TITLE
terminal hangs when creating a new app

### ISSUE THREAD

**Issue by kerolloz** [strongloop/loopback-cli#88]
## Description / Steps to reproduce / Feature proposal

I just write 
```shell
lb app
```
in my terminal.  

## Current Behavior

After entering the project name, my terminal stops(hangs), the cursor keeps blinking, and doesn't accept any input at `? Enter the name of the directory to contain the project: (test)` question. 
I tried pressing `<Enter>`, `Ctrl+Z`, `Ctrl+C` or `any button` but, unfortunately, has no effect.

![screenshot](https://user-images.githubusercontent.com/36763164/59863172-73d7cf00-9384-11e9-9891-8cae945e0be3.png)

## Expected Behavior

I should be able to enter the project root directory.

## Note

I have just installed loopback CLI, using the following command.

```shell
sudo npm i -g loopback-cli
```
I use Ubuntu 19.04.

**Comment by keks411** [comment]
Same issue here. To give some more info:

OS: Ubuntu 18.04.2
Node: v12.4.0
npm: 6.9.0
5.0.0 (generator-loopback@6.0.4 loopback-workspace@5.0.0)

I also tried the same with the LTS-Node-Version and Node10 and Node12 with Centos7. Same issue.

**Comment by jannyHou** [comment]
looking, might be the same reason as https://github.com/strongloop/loopback-next/issues/3187

**Comment by dhmlau** [comment]
We've released a new version of `@loopback/cli` (1.17.1) that fixes on the `inquirer` version.  Please update to the latest version. Thanks.

**Comment by kerolloz** [comment]
@jannyHou 
Thank you :smiley:

**Comment by jannyHou** [comment]
released in 5.0.3, let me know if it still fails.

**Comment by kerolloz** [comment]
@jannyHou 
it works perfectly :100:  thank you :tada:

**Comment by jannyHou** [comment]
yw :)
