### ISSUE TITLE
Any interest in a REPL/console command?

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback-cli#9]
I published some time ago https://github.com/doublemarked/loopback-console, which is a Loopback-aware node REPL that does a few things,

  - Loads up a Loopback app discovered from the cwd
  - Binds the app and all its models into the repl's context
  - Auto-resolves promises

We've found it quite useful during development to quickly prototype things or poke around at the app, and at times to manipulate data in a production environment similar to an admin console. 

Would there be interest in a PR to merge this functionality into loopback-cli? The loopback-console functions similarly to the cli, in that it operates on whatever loopback app it can find from the cwd.

**Comment by raymondfeng** [comment]
@doublemarked That would be a good addition to loopback-cli!

**Comment by doublemarked** [comment]
Hey guys - happy to hear the interest. I've spent a little time reviewing the `loopback-cli` code to understand how it might fit in. I see that currently the cli project is just a thin CLI wrapper around `strongloop/generator-loopback`. I'd like to propose the repl be incorporated in a similar way,

  1. I add some tests to the `loopback-console` project to bring it up to standards.
  2. The cli includes the `loopback-console` as a dependency. This can include either a fork and transfer to Strongloop of ownership of `loopback-console` in the npm registry or we could rename it to something like `loopback-repl`. As you prefer.
  3. Similar to the generator commands, we add a command like `lb repl` or `lb console` to the cli which just defers to the `loopback-console` dep.

**Comment by superkhau** [comment]
I like the idea of `loopback-repl` based on your `loopback-console` project. Integrating it via `lb repl` makes sense (and is shorter to type in general). LGTM. :shipit:
