### ISSUE TITLE
unable to run project .

### ISSUE THREAD

**Issue by cs-akash-jarad** [strongloop/loopback-cli#90]
npm WARN deprecated swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 381 packages from 428 contributors and audited 2329 packages in 8.162s
found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

steps :
lb
? What's the name of your application? jsmeetup
? Which version of LoopBack would you like to use? 3.x (Active Long Term Support)
? What kind of application do you have in mind? notes (A project containing a basic working example, including a memory database)

<img width="669" alt="Screenshot 2019-06-21 at 16 39 06" src="https://user-images.githubusercontent.com/36440805/59918730-3be39100-9443-11e9-8155-f94464b93970.png">

**Comment by dhmlau** [comment]
@bajtos, I believe you're looking into this. Assigning this to you. Thanks.

**Comment by bajtos** [comment]
Please note the security report is just advisory, it does not prevent the application from running.

We are discussing the vulnerabilities in https://github.com/strongloop/loopback-component-explorer/issues/263.

Closing this issue as a duplicate.
