### ISSUE TITLE
updating to ES6

### ISSUE THREAD

**Issue by devpato** [strongloop/loopback-cli#93]
Root.js and Server.js still using var instead of const/let. And some other parts of the project should be updated to start using ES6.

**Comment by dhmlau** [comment]
@devpato, we're gradually moving to use ES6 amongst the LB repos.  Would you be interested to submit a patch for this repo or others if you find it's needed?

**Comment by devpato** [comment]
yes for sure! I will take a look to the contribution agreement. Do you have anything else I should take a look at?

**Comment by dhmlau** [comment]
Thanks! 

If you're new to contributing to LB, you might want take a look at https://loopback.io/doc/en/contrib/code-contrib.html for reference. There's a [step-by-step instruction](https://loopback.io/doc/en/lb4/submitting_a_pr.html) for submitting a PR, but it's a bit tailored to LB4, so the instruction might vary a bit.
