### ISSUE TITLE
LICENSE file is ambiguous

### ISSUE THREAD

**Issue by jeremiah** [strongloop/loopback-cli#97]
# Description/Steps to reproduce
1. Open license file in GitHub repo for loopback-cli

# Link to reproduction sandbox
See above.

https://github.com/strongloop/loopback-cli/blob/master/LICENSE
# Expected result
LICENSE is clear and concise and clearly denotes which open source rights are granted.

# Additional information
https://github.com/strongloop/loopback-cli/blob/master/LICENSE
In this file you write "All rights reservered." But you're not reserving all rights. You're explicitly granting some rights, like copying the source code. FWIW "All rights reserved" doesn't possess any legal weight and can safely be removed.

**Comment by raymondfeng** [comment]
I'm not a legal person. But it should be fine to have the copyright statement per https://opensource.org/licenses/MIT. 

Are you proposing to simply remove `All rights reserved`?

**Comment by jeremiah** [comment]
Yep! :-) Simply remove that line and everything is cool. This will make it a bit easier for finicky legal folks to use your software.

**Comment by jeremiah** [comment]
The copyright and license statement from Opensource.org is great (and quite frankly as long as you've done the copyright statement right, it's all you need.)

**Comment by dhmlau** [comment]
Besides the [LICENSE file](https://github.com/strongloop/loopback-cli/blob/master/LICENSE), the copyright headers of the source code also contains the "All rights reserved". 

@rmg, do you think we can modify the `slt copyright` command in `strong-tools`? 
I'm looking at some other open source projects from IBM, and they also don't have the "All rights reserved" phrase in the header as well.
https://github.com/IBM/nodejs-itoolkit/blob/master/lib/ProgramCall.js
https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js

**Comment by dhmlau** [comment]
@jeremiah, can I assume that you're a new LoopBack 3 user? Would you consider the more recent version LB4 instead? https://github.com/strongloop/loopback-next/. 
I'm suggesting this because LoopBack 3 will go end of life at the end of Dec, if you're starting out on using LB, LB4 would be a better choice. https://loopback.io/doc/en/lb4/. (Note: the LICENSE is the same).

**Comment by jeremiah** [comment]
I'm not a loopback user sadly, I'm an open source technologist helping companies use open source. :-)
I will recommend the usage of a later version of loopback. :heavy_check_mark:

**Comment by rmg** [comment]
The `All rights reserved` is indeed unnecessary. Reviewing the history, it looks like the policy docs I was following at the time had not been updated to reflect that so I erred on the side of caution.
