### ISSUE TITLE
remote-method command does nothing

### ISSUE THREAD

**Issue by sujeshthekkepatt** [strongloop/loopback-cli#99]
# Description/Steps to reproduce

lb remote-method shows ```Run-async wrapped function (sync) returned a promise but async() callback must be executed to resolve.``` and does nothing.

Steps for reproduction,
 1. Install loopback-cli
2. On an existing project run `lb remote-method`
3. Give method name, description now we can see the message above. 

# Link to reproduction sandbox

# Expected result
The remote method should have created.

# Additional information

Platform : `ubuntu (linux x64)`
Node version: `12.16.1`
loopback info : ```+-- loopback@3.26.0
+-- loopback-boot@2.27.1
+-- loopback-component-explorer@6.3.0
+-- loopback-connector-postgresql@2.9.0
+-- loopback-ds-timestamp-mixin@3.4.1
```

**Comment by emonddr** [comment]
@sujeshthekkepatt , please provide a minimal application to demonstrates this problem so we can investigate. thank you.

**Comment by sskhokhar** [comment]
Im facing same issue

**Comment by sskhokhar** [comment]
Anyone able to resolved this issue?

**Comment by hamedebrahimi** [comment]
Facing same problem on macOS!
When using lb remote-method after "Description for method" step this message shows up:
"Enter the path of this endpoint: Run-async wrapped function (sync) returned a promise but async() callback must be executed to resolve. "
And similar thing happen at "What is the name of this argument?" step :
"Run-async async() called outside a valid run-async context, callback will be ignored."
